#!/bin/bash env
# script that sets up a few firewall rules on web-01.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw default deny incoming
sudo ufw enable
